### ISSUE TITLE
Output folder and file name

### ISSUE THREAD

**Issue by darjacvetkovic** [polcolomer/RandNetGen#10]
Hi, thank you for the code! I was wondering if there is a way to specify the output file directory, and/or the file name, without changing the source code? ( I'm unfamiliar with C syntax )

**Comment by polcolomer** [comment]
Hi darja,

Thanks for your interes in randnetgen.
Im sorry but there is no parameter to set the outputfile name without
changinf the C source code. However, you can always, change the name by
hand, or by a bash script that call randnetgen and then change
automatically the name of the outputfile.

Hope that helps

Pol

El dv., 18 de nov. 2022, 21:00, Darja Cvetkovic ***@***.***>
va escriure:

**Comment by darjacvetkovic** [comment]
Thank you for the quick response and advice! Yes, I figured that I could do it in a bash script :) Thanks again!
