### ISSUE TITLE
Typo in main.c

### ISSUE THREAD

**Issue by antoineallard** [polcolomer/RandNetGen#4]
On line 299 in file main.c, the argument of the if statement should read `*pkk` instead of `pkk` (i.e., the asterisk is missing). This typo makes it impossible to use the `-knn` option since an error is always triggered.

I may be contributing to this project later this month, so I could correct the typo myself, if you agree.

**Comment by polcolomer** [comment]
Ok! Moltes gràcies! Demà mho miro!!
