### ISSUE TITLE
Segmentation Fault on execution

### ISSUE THREAD

**Issue by sameeravithana** [polcolomer/RandNetGen#6]
<img width="821" alt="screen shot 2017-05-27 at 12 09 37 am" src="https://cloud.githubusercontent.com/assets/2469897/26517896/d2b65990-4270-11e7-9eca-9b5f7674480e.png">

**Comment by polcolomer** [comment]
Hey Sam! Thanks for sharing your problem! I will have a look at it as soon as i can! If its possible, could you could send me the edgelist file terror_edges.txt? 
Thanks and i'll be back to you soon!

Pol

**Comment by sameeravithana** [comment]
Hey Pol, Here is the edgelist file.
[terrornet.txt](https://github.com/polcolomer/RandNetGen/files/1036149/terrornet.txt)

**Comment by polcolomer** [comment]
Hey Sam!! sorry for the delay! i just make a pull request and run the program and it just worked fine!
Which OS are you using?
![screenshot](https://user-images.githubusercontent.com/8222770/27737775-b236f4fa-5da9-11e7-920b-f58b530b2952.png)

**Comment by polcolomer** [comment]
I raed on the internet that it can be a mis interpretation of tabs and spaces. In my program i assume that there is a tab between the two columns of the input edgelist. However, at least in linux, it works of there is a space. Try to put a tab between the columns and let's see if it works.
I founs another person with the same problem. Thanks for your report and let's see if we can figure out the problem!

**Comment by sameeravithana** [comment]
I think, there seems to be the fault on reading the path of the edgelist, whenever the edgelist file is local to repo, this works fine.
<img width="710" alt="screen shot 2017-06-30 at 9 58 35 am" src="https://user-images.githubusercontent.com/2469897/27738953-fef94484-5d7a-11e7-9a2c-654f2d93a81d.png">

**Comment by sameeravithana** [comment]
How unique this implementation, when comparing with [1]
[1] http://www.minasgjoka.com/2.5K/instructions/index.html

**Comment by polcolomer** [comment]
Yes! you are right!! Thank you so much for this!! I will try to fix it!
Sorry for the delay again and hope that you found RandNetGen useful!
