### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by WZPBelieveFuture** [polcolomer/RandNetGen#8]
When I carry out the command"./RandNetGen -net netFILEname -dk 2.1",it turns out "Reading the network...
Segmentation fault (core dumped)"

**Comment by WZPBelieveFuture** [comment]
I wonder how to slove the problem

**Comment by WZPBelieveFuture** [comment]
I wonder how to solve the problem

**Comment by polcolomer** [comment]
Hey @WZPBelieveFuture sorry for the delay. I was on vacation without internet access.
The most probable reason for your error is the format of the input network file is incorrect. Check the appropriate format at the readme file. Try it again and come to me if you have problems.
