### ISSUE TITLE
Error reading a link 

### ISSUE THREAD

**Issue by HKris-21** [polcolomer/RandNetGen#9]
Hello ,
I get this error when i try to run your code , the file Interactor_list.txt contains two columns with edges .
Operating system is Fedora.  

./RandNetGen -net Interactor_list.txt

ARGUMENTS:
   Network : Interactor_list.txt
   Preserving the P(k)
   Num of rewires x step : 100*E
   Initial beta : 100.000000
   Beta increment : 1.400000
   Min acceptation rate : 0.000050
   Random seed 1612420190

Reading the network...
error reading a link form the edge list(This keeps on repeating)

**Comment by polcolomer** [comment]
Hi Harikrishnan,

thanks for using my code, 

Remember that the file should be in the edge list format: A plain text file with two numeric columns with all the edges (origin, destination). With or without repetitions. Undirected and unweighted networks only.

thanks,

Pol

**Comment by HKris-21** [comment]
Hi Pol ,
It was a silly mistake from my side.
The code works like a charm.
Thank you for your time and sorry for the trouble.
